In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("food_delivery.csv")

In [4]:
df.head()

,order_id,customer_id,customer_name,restaurant_name,food_item,food_category,quantity,unit_price,total_amount,order_date,order_time,delivery_time_minutes,city,customer_rating,payment_method,delivery_status
0,1,1201,Rahul Sharma,Pizza Hut,Veg Pizza,Pizza,2,250.0,500.0,2025-08-01,18:30:00,35,Mumbai,4.5,UPI,Delivered
1,2,1202,Priya Patil,Dominos,Farmhouse Pizza,Pizza,1,450.0,450.0,2025-08-02,19:15:00,28,Pune,4.8,Card,Delivered
2,3,1203,Amit Jadhav,KFC,Chicken Bucket,Fast Food,1,650.0,650.0,2025-08-03,20:10:00,42,Nashik,4.2,Cash,Delivered
3,4,1204,Sneha More,McDonalds,French Fries,Snacks,3,90.0,270.0,2025-08-04,17:45:00,22,Nagpur,4.1,UPI,Delivered
4,5,1205,Rohan Patil,Subway,Paneer Sandwich,Healthy,2,230.0,460.0,2025-08-05,13:20:00,24,Thane,4.6,Card,Delivered

In [5]:
df.tail()

,order_id,customer_id,customer_name,restaurant_name,food_item,food_category,quantity,unit_price,total_amount,order_date,order_time,delivery_time_minutes,city,customer_rating,payment_method,delivery_status
495,496,1696,Harshal Shah,KFC,Hot Crispy Chicken,Fast Food,2,365.0,730.0,2026-12-07,19:55:00,39,Nagpur,4.5,Card,Delivered
496,497,1697,Deepali More,Dominos,Cheese n Corn Pizza,Pizza,1,415.0,415.0,2026-12-08,20:25:00,28,Thane,4.5,UPI,Delivered
497,498,1698,Akash Patil,McDonalds,French Fries,Snacks,4,135.0,540.0,2026-12-09,17:15:00,20,Mumbai,4.1,Cash,delivered
498,499,1699,Rohit Shah,Subway,Paneer Tikka Sandwich,Healthy,2,300.0,600.0,2026-12-10,13:25:00,24,Pune,4.7,Card,Delivered
499,500,1700,Neha More,Burger King,Cheese Burger,Burger,2,240.0,480.0,2026-12-11,15:35:00,28,Nashik,4.2,UPI,Delivered

In [6]:
df.shape

(500, 16)

In [7]:
df.columns

Index(['order_id', 'customer_id', 'customer_name', 'restaurant_name',
       'food_item', 'food_category', 'quantity', 'unit_price', 'total_amount',
       'order_date', 'order_time', 'delivery_time_minutes', 'city',
       'customer_rating', 'payment_method', 'delivery_status'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               500 non-null    int64
 1   customer_id            500 non-null    int64
 2   customer_name          500 non-null    object
 3   restaurant_name        500 non-null    object
 4   food_item              500 non-null    object
 5   food_category          500 non-null    object
 6   quantity               500 non-null    int64
 7   unit_price             500 non-null    float64
 8   total_amount           500 non-null    float64
 9   order_date             500 non-null    object
 10  order_time             500 non-null    object
 11  delivery_time_minutes  500 non-null    int64
 12  city                   500 non-null    object
 13  customer_rating        480 non-null    float64
 14  payment_method         490 non-null    object
 15  delivery_status        500 non-null    object
dtypes: float64(3), int64(4), object(9)
memory usage: 62.6+ KB

In [9]:
df.describe

<bound method NDFrame.describe of      order_id  customer_id customer_name restaurant_name  \
0           1         1201  Rahul Sharma       Pizza Hut
1           2         1202   Priya Patil         Dominos
2           3         1203   Amit Jadhav             KFC
3           4         1204    Sneha More       McDonalds
4           5         1205   Rohan Patil          Subway
..        ...          ...           ...             ...
495       496         1696  Harshal Shah             KFC
496       497         1697  Deepali More         Dominos
497       498         1698   Akash Patil       McDonalds
498       499         1699    Rohit Shah          Subway
499       500         1700     Neha More     Burger King

                 food_item food_category  quantity  unit_price  total_amount  \
0                Veg Pizza         Pizza         2       250.0         500.0
1          Farmhouse Pizza         Pizza         1       450.0         450.0
2           Chicken Bucket     Fast Food         1       650.0         650.0
3             French Fries        Snacks         3        90.0         270.0
4          Paneer Sandwich       Healthy         2       230.0         460.0
..                     ...           ...       ...         ...           ...
495     Hot Crispy Chicken     Fast Food         2       365.0         730.0
496    Cheese n Corn Pizza         Pizza         1       415.0         415.0
497           French Fries        Snacks         4       135.0         540.0
498  Paneer Tikka Sandwich       Healthy         2       300.0         600.0
499          Cheese Burger        Burger         2       240.0         480.0

     order_date order_time  delivery_time_minutes    city  customer_rating  \
0    2025-08-01   18:30:00                     35  Mumbai              4.5
1    2025-08-02   19:15:00                     28    Pune              4.8
2    2025-08-03   20:10:00                     42  Nashik              4.2
3    2025-08-04   17:45:00                     22  Nagpur              4.1
4    2025-08-05   13:20:00                     24   Thane              4.6
..          ...        ...                    ...     ...              ...
495  2026-12-07   19:55:00                     39  Nagpur              4.5
496  2026-12-08   20:25:00                     28   Thane              4.5
497  2026-12-09   17:15:00                     20  Mumbai              4.1
498  2026-12-10   13:25:00                     24    Pune              4.7
499  2026-12-11   15:35:00                     28  Nashik              4.2

    payment_method delivery_status
0              UPI       Delivered
1             Card       Delivered
2             Cash       Delivered
3              UPI       Delivered
4             Card       Delivered
..             ...             ...
495           Card       Delivered
496            UPI       Delivered
497           Cash       delivered
498           Card       Delivered
499            UPI       Delivered

[500 rows x 16 columns]>

In [10]:
df.isnull().sum()

order_id                  0
customer_id               0
customer_name             0
restaurant_name           0
food_item                 0
food_category             0
quantity                  0
unit_price                0
total_amount              0
order_date                0
order_time                0
delivery_time_minutes     0
city                      0
customer_rating          20
payment_method           10
delivery_status           0
dtype: int64

In [11]:
df['customer_rating'] = df['customer_rating'].fillna(
    df['customer_rating'].mean()
)

In [12]:
df['payment_method'] = df['payment_method'].fillna(
    'Unknown'
)

In [13]:
df['delivery_status'] = df['delivery_status'].str.capitalize()

In [14]:
df.isnull().sum()

order_id                 0
customer_id              0
customer_name            0
restaurant_name          0
food_item                0
food_category            0
quantity                 0
unit_price               0
total_amount             0
order_date               0
order_time               0
delivery_time_minutes    0
city                     0
customer_rating          0
payment_method           0
delivery_status          0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.isnull().sum()

order_id                 0
customer_id              0
customer_name            0
restaurant_name          0
food_item                0
food_category            0
quantity                 0
unit_price               0
total_amount             0
order_date               0
order_time               0
delivery_time_minutes    0
city                     0
customer_rating          0
payment_method           0
delivery_status          0
dtype: int64

In [18]:
df.to_csv(
    "clean_food_delivery.csv",
    index=False
)

In [19]:
df.head()

,order_id,customer_id,customer_name,restaurant_name,food_item,food_category,quantity,unit_price,total_amount,order_date,order_time,delivery_time_minutes,city,customer_rating,payment_method,delivery_status
0,1,1201,Rahul Sharma,Pizza Hut,Veg Pizza,Pizza,2,250.0,500.0,2025-08-01,18:30:00,35,Mumbai,4.5,UPI,Delivered
1,2,1202,Priya Patil,Dominos,Farmhouse Pizza,Pizza,1,450.0,450.0,2025-08-02,19:15:00,28,Pune,4.8,Card,Delivered
2,3,1203,Amit Jadhav,KFC,Chicken Bucket,Fast Food,1,650.0,650.0,2025-08-03,20:10:00,42,Nashik,4.2,Cash,Delivered
3,4,1204,Sneha More,McDonalds,French Fries,Snacks,3,90.0,270.0,2025-08-04,17:45:00,22,Nagpur,4.1,UPI,Delivered
4,5,1205,Rohan Patil,Subway,Paneer Sandwich,Healthy,2,230.0,460.0,2025-08-05,13:20:00,24,Thane,4.6,Card,Delivered

In [20]:
df.to_csv(r"C:\Users\Harsh\Desktop\clean_food_delivery.csv", index=False)

In [21]:
import os

print(os.getcwd())

c:\Users\Harsh\OneDrive\Desktop\codempower\Python

In [22]:
import os

print(os.path.exists(r"C:\Users\Harsh\Desktop\clean_food_delivery.csv"))

True

In [23]:
import os

print(os.getcwd())

c:\Users\Harsh\OneDrive\Desktop\codempower\Python